version: "3.8"
volumes:
  redis_data: {}
services:
  postgres:
    container_name: dms-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: users-api
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: dms-redis
    image: "docker.io/bitnami/redis"
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: root
      REDIS_AOF_ENABLED: "no"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  dms-api:
    container_name: dms-api
    build: ./api/dms
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: "host=postgres user=root password=root dbname=dms sslmode=disable"
      PORT: 3000
      REDIS_URL: "redis:6379"
      REDIS_PASSWORD: "root"
      MQTT_CLIENT_ID: "DMS"
      JWT_SECRET: "dmsSecret"
      AZURE_STORAGE_ACCOUNT_NAME: "AZURE_STORAGE_ACCOUNT_KEY"
      AZURE_STORAGE_ACCOUNT_KEY: "AZURE_STORAGE_ACCOUNT_KEY"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://dms-api/health"]
  dms-web:
    container_name: dms-web
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - dms-api
    environment:
      VUE_APP_API_URL: "http://dms-api/api"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://dms-frontend"]
